version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  install:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - attach_workspace:
          at: ~/repo
      - run:
          name: Linting
          command: npm run lint -- --format junit --output reports/junit/tslint-results.xml
      - persist_to_workspace:
          root: ~/repo
          paths:
            - reports/junit
  test:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - attach_workspace:
          at: ~/repo
      - run:
          name: Unit tests
          command: npm test -- --coverage --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/jest-results.xml'
      - persist_to_workspace:
          root: ~/repo
          paths:
            - coverage
            - reports/junit
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - lib
  coverage:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Coverage
          command: npx codecov
      - store_test_results:
          path: reports/junit
  deploy:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Prepare deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                sudo npm install -g firebase-tools
            fi
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run deploy -- --token "$FIREBASE_TOKEN"
            fi
workflows:
  version: 2
  main:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - coverage:
          requires:
            - lint
            - test
      - deploy:
          requires:
            - lint
            - test
            - build
