name: PR Checks

on:
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v1
        env:
          cache-name: cache-node_modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run lint -- --format junit
      - run: npm test -- --coverage
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
          name: Coverage
          fail_ci_if_error: true
      - run: npm run build
        env:
          CI: true
